packages:
  - apps/*
  - internal-packages/*
  - packages/*
  - tools/*

catalog:
  '@ai-sdk/anthropic': 2.0.17
  '@ai-sdk/fal': 1.0.13
  '@ai-sdk/gateway': 1.0.23
  '@ai-sdk/google': 2.0.16
  '@ai-sdk/google-vertex': 3.0.29
  '@ai-sdk/openai': 2.0.30
  '@ai-sdk/perplexity': 2.0.9
  '@ai-sdk/provider': 2.0.0
  '@ai-sdk/react': 2.0.44
  '@aws-sdk/client-s3': 3.842.0
  '@biomejs/biome': 2.0.6
  '@embedpdf/pdfium': 1.2.1
  '@fal-ai/client': 1.3.0
  '@graphql-codegen/cli': 5.0.5
  '@graphql-codegen/client-preset': 4.7.0
  '@next/env': 15.5.2
  '@next/third-parties': 15.5.2
  '@octokit/auth-app': 8.0.1
  '@octokit/core': 7.0.2
  '@octokit/graphql': 9.0.1
  '@octokit/openapi-types': 25.1.0
  '@octokit/request-error': 7.0.0
  '@octokit/webhooks': 14.0.2
  '@radix-ui/react-tabs': 1.1.2
  '@supabase/auth-js': 2.70.0
  '@supabase/ssr': 0.6.1
  '@supabase/supabase-js': 2.50.5
  '@tailwindcss/postcss': 4.1.10
  '@tailwindcss/typography': 0.5.16
  '@tiptap/core': 2.11.5
  '@tiptap/extension-code-block-lowlight': 2.11.5
  '@tiptap/extension-placeholder': 2.11.5
  '@tiptap/html': 2.11.5
  '@tiptap/pm': 2.11.5
  '@tiptap/react': 2.11.5
  '@tiptap/starter-kit': 2.11.5
  '@trigger.dev/sdk': 4.0.4
  '@turbo/gen': 2.3.3
  '@types/fast-levenshtein': 0.0.4
  '@types/node': 22.14.0
  '@types/pg': 8.11.13
  '@types/pluralize': 0.0.33
  '@types/pngjs': 6.0.5
  '@types/react': 19.1.10
  '@types/react-dom': 19.1.7
  '@types/tar': 6.1.13
  '@types/turndown': 5.0.5
  '@urql/core': 5.1.1
  '@vercel/edge-config': 1.4.0
  '@vercel/functions': 2.2.11
  '@xyflow/react': 12.8.3
  ai: 5.0.51
  clsx: 2.1.1
  defuddle: 0.6.4
  fast-levenshtein: 3.0.0
  gql.tada: 1.8.10
  graffle: 8.0.0-next.157
  graphql: 16.10.0
  happy-dom: 17.6.1
  highlight.js: 11.11.1
  jsdom: 26.1.0
  langfuse: 3.38.4
  langfuse-core: 3.38.4
  lowlight: 3.3.0
  lucide-react: 0.473.0
  marked: 15.0.7
  motion: 12.3.1
  nanoid: 5.0.9
  next: 15.5.2
  node-loader: 2.1.0
  nuqs: 2.6.0
  openai: 5.11.0
  pg: 8.14.1
  pgvector: 0.2.1
  pino: 9.9.0
  pluralize: 8.0.0
  pngjs: 7.0.0
  postcss: 8.5.5
  radix-ui: 1.1.2
  react: 19.1.1
  react-dom: 19.1.1
  react-markdown: 9.0.3
  react-resizable-panels: 2.1.7
  swr: 2.3.6
  tailwindcss: 4.1.10
  tailwindcss-animate: 1.0.7
  tar: 7.4.3
  tsup: 8.3.5
  turndown: 7.2.0
  typescript: 5.7.3
  unstorage: 1.14.4
  urql: 4.2.2
  vitest: 3.2.4
  zod: 3.25.76
  zustand: 5.0.8

minimumReleaseAge: 1440
