name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Biome
        uses: biomejs/setup-biome@454fa0d884737805f48d7dc236c1761a0ac3cc13 # v2.6.0
        with:
          version: 2.0.6
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - run: pnpm install
      - name: Set node version to 22.14.0
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22.14.0
          cache: "pnpm"
      - name: Run Biome
        run: biome ci .
      - run: pnpm knip
      - name: Build SDK
        run: pnpm build-sdk
      - name: Install ripgrep (rg)
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Report Colors (non-blocking)
        run: pnpm report:colors
        continue-on-error: true
      - name: Save Report Colors JSON
        if: always()
        run: pnpm report:colors:out || true
      - name: Upload Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-colors
          path: .reports/report-colors.json
      - name: Guard Colors (non-blocking warnings)
        run: pnpm guard:colors -- --baseline .reports/report-colors.json || true
      - name: Test
        run: pnpm test
