name: Claude Code

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt to send to Claude"
        required: true
        type: string

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install -g @anthropic-ai/claude-code
      - run: claude -p "${{ github.event.inputs.prompt }}"
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
